# Schema for the configuration files of the GridStack module.
gridstack.settings:
  type: config_object
  label: 'GridStack settings'
  mapping:
    customized:
      type: boolean
      label: 'Use customized GridStack library'
    jquery_ui:
      type: boolean
      label: 'Load jQuery UI library'

# The grids.
gridstack_node:
  type: mapping
  label: 'Grid nodes'
  mapping:
    x:
      type: integer
      label: 'X'
    y:
      type: integer
      label: 'Y'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
    image_style:
      type: string
      label: 'Image style'

gridstack_grid:
  type: sequence
  label: 'Grids'
  sequence:
    - type: mapping
      mapping:
        node:
          type: gridstack_node
          label: 'Nodes'
        nested:
          type: sequence
          label: 'Nested'
          sequence:
            - type: string

gridstack_json:
  type: mapping
  label: 'JSON'
  mapping:
    grids:
      type: sequence
      label: 'Grids'
      sequence:
        - type: string
    settings:
      type: string
      label: 'Settings'
    breakpoints:
      type: string
      label: 'Breakpoints'

gridstack_breakpoint:
  type: mapping
  mapping:
    breakpoint:
      type: string
      label: 'Breakpoint'
    column:
      type: integer
      label: 'Column'
    image_style:
      type: string
      label: 'Image style'
    width:
      type: integer
      label: 'Width'
    grids:
      type: string
      label: 'Grids'

gridstack_breakpoints:
  type: mapping
  label: 'Breakpoints'
  mapping:
    xs:
      type: gridstack_breakpoint
      label: 'XS'
    sm:
      type: gridstack_breakpoint
      label: 'SM'
    md:
      type: gridstack_breakpoint
      label: 'MD'
    lg:
      type: gridstack_breakpoint
      label: 'LG'

# GridStack JS settings managed by UI.
gridstack_optionset:
  type: mapping
  label: 'Options'
  mapping:
    breakpoints:
      type: gridstack_breakpoints
    grids:
      type: gridstack_grid
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        alwaysShowResizeHandle:
          type: boolean
          label: 'Always show resize handle'
        auto:
          type: boolean
          label: 'Auto'
        cellHeight:
          type: integer
          label: 'Cell height'
        disableDrag:
          type: boolean
          label: 'Disable drag'
        disableResize:
          type: boolean
          label: 'Disable resize'
        draggable:
          type: boolean
          label: 'Draggable'
        float:
          type: boolean
          label: 'Float'
        isNested:
          type: boolean
          label: 'isNested'
        minWidth:
          type: integer
          label: 'Min width'
        width:
          type: integer
          label: 'Width'
        height:
          type: integer
          label: 'Height'
        resizable:
          type: boolean
          label: 'Resizable'
        rtl:
          type: boolean
          label: 'RTL'
        staticGrid:
          type: boolean
          label: 'staticGrid'
        verticalMargin:
          type: integer
          label: 'Vertical margin'
        noMargin:
          type: boolean
          label: 'No horizontal margin'

# Individual GridStack JS settings managed by UI.
gridstack.optionset.*:
  type: config_entity
  label: 'GridStack optionset'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    weight:
      type: integer
      label: 'Weight'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    json:
      type: gridstack_json
    options:
      type: gridstack_optionset
      label: 'Options'

# HTML content/layout-related settings managed by GridStack plugins.
gridstack_base:
  type: blazy_base
  label: 'GridStack display format base settings'
  mapping:
    caption:
      type: sequence
      label: 'Captions'
      sequence:
        - type: string
          label: 'Caption field'
    stamp:
      type: sequence
      label: 'Stamps'
      sequence:
        - type: string

views.style.gridstack:
  type: gridstack_base
  label: 'GridStack'
  mapping:
    id:
      type: string
      label: 'GridStack ID'
