<?php

/**
 * @file
 * Provides GridStack examples.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_gridstack_skins_info().
 *
 * To provide own skins, simply provide the legit class namespace, and the class
 * must implement \Drupal\gridstack\GridStackSkinInterface.
 *
 * @see \Drupal\gridstack\GridStackSkinInterface
 */
function gridstack_example_gridstack_skins_info() {
  return '\Drupal\gridstack_example\GridStackExampleSkin';
}

/**
 * Implements hook_help().
 */
function gridstack_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.gridstack_example':
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}
